import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600']
})

import Header from '@/components/header'
import * as filterContexts from '@/contexts/filter-context'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <filterContexts.FilterContextProvider>
          <Header />
          {children}
        </filterContexts.FilterContextProvider>
      </body>
    </html>
  )
}
